<?php
$css=array(
    'bootstrap.min',
    'font-awesome',
    'animate',    
    'jquery-ui',
    'magnific-popup',
    'jAlert-v3',
    'layerslider',
    'slick',
    'slick-theme',
    'flexslider',
    'ribbon',
    'nice-tabs',
    'speech-bubbles',
    'self'
);
$js=array(
    'jquery',
    'jquery-ui',
    'jquery-migrate',
    'bootstrap.min',
    'validator.min',
    'jquery.magnific-popup',
    'jAlert-v3',
    'jAlert-functions',
    'jquery.isotope.min',
    'layerslider',
    'layerslider.greensock',
    'layerslider.transitions',
    'wow',
    'slick.min',
    'jquery.flexslider',
    'self'
);
include_once 'config.php';
include_once 'lang/'.$lang.'.php';
define('limit',10);
define('pd_lim',12);
?>